CREATE TABLE tb_categoria (
    id int GENERATED BY DEFAULT AS IDENTITY,
    nome varchar(150) not null,
    PRIMARY KEY (id)
);

CREATE TABLE tb_produto (
    id int GENERATED BY DEFAULT AS IDENTITY,
    nome varchar(150) not null,
    codigo_barras varchar(25) not null,
    valor int,
    descricao varchar(350) not null,
    quantidade int,
    categoria_id int,
    PRIMARY KEY (id),
    FOREIGN KEY (categoria_id) REFERENCES tb_categoria(id)
);